name: Auto Update Clean IPs

# تنظیم زمان‌بندی اجرا
on:
  schedule:
    - cron: '0 */6 * * *' # هر ۶ ساعت یک‌بار اجرا می‌شود
  workflow_dispatch: # اضافه کردن دکمه اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Aggregator Script
        run: python aggregate.py

      - name: Commit and Push output
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add my-clean-ips.json
          git commit -m "Auto-update clean IPs" || echo "No changes to commit"
          git push
